# Generated by Django 5.2 on 2025-05-12 14:30

import messages_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0002_alter_audiomessage_text_alter_imagemessage_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[messages_api.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videomessage',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
