# Generated by Django 5.2 on 2025-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0003_alter_audiomessage_text_alter_imagemessage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiomessage',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videomessage',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
