name: Deploy to EC2

on:
    push:
        branches:
            - main # or your default branch
        paths:
            - "backend/**" # Only trigger on changes in backend directory

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      # Navigate to the project directory
                      cd /home/ubuntu/Incognito/backend

                      # Pull the latest changes
                      git pull origin main

                      # Activate virtual environment
                      source venv/bin/activate

                      # Install/update dependencies
                      pip install -r requirements.txt

                      # Collect static files
                      python manage.py collectstatic --noinput

                      # Check if nginx config has changed
                      if ! cmp -s nginx/incognito.conf /etc/nginx/sites-available/incognito.conf; then
                        echo "Nginx configuration has changed, updating..."
                        sudo cp nginx/incognito.conf /etc/nginx/sites-available/
                        sudo ln -sf /etc/nginx/sites-available/incognito.conf /etc/nginx/sites-enabled/
                        sudo nginx -t && sudo systemctl restart nginx
                      fi

                      # Restart Gunicorn service
                      sudo systemctl restart incognito.service

                      # Check service status
                      sudo systemctl status incognito.service
